version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 172.25.0.3

  backend:
    depends_on:
      - db
    image: herbalsomml/webcam_studio_catalog
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    networks:
      vpcbr:
        ipv4_address: 172.25.0.4

  gateway:
    depends_on:
      - backend
    image: herbalsomml/webcam_studio_catalog_gateway
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/var/html/media
      - /etc/ssl/mycamhub.pem:/etc/ssl/mycamhub.pem
      - /etc/ssl/mycamhub.key:/etc/ssl/mycamhub.key
    networks:
      vpcbr:
        ipv4_address: 172.25.0.5

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24