version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build: ./website/
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media

  gateway:
    depends_on:
      - backend
    build:
      ./gateway/
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/var/html/media
      - /etc/ssl/mycamhub.pem:/etc/ssl/mycamhub.pem
      - /etc/ssl/mycamhub.key:/etc/ssl/mycamhub.key