# Generated by Django 4.2.13 on 2024-06-11 14:17

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_alter_miniad_large_image_alter_miniad_medium_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=mdeditor.fields.MDTextField(verbose_name='Полное описание'),
        ),
    ]
