# Generated by Django 4.2.13 on 2024-05-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_city_options_alter_experiencechoices_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miniad',
            options={'verbose_name': 'Мини реклама', 'verbose_name_plural': 'Мини реклама'},
        ),
    ]
